### ISSUE TITLE
TO-DO LIST

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty-Lua#1]
- [ ] Finish translating GUMS
- [ ] Translate Save/Load System (partially)
- [ ] Translate Decoration SFX system
- [ ] Fiinish translating Save/Load System
